### ISSUE TITLE
Features to add to Darius without compromising the simple design

### ISSUE THREAD

**Issue by AriaSalvatrice** [AriaSalvatrice/AriaVCVModules#10]
See #8 for plans to possibly make a more featured device.

- Voltage range selection
- Accept polyphonic triggers

**Comment by Miserlou** [comment]
I'm curious what it would sound like if it could run backwards.

**Comment by Chaircrusher** [comment]
> Voltage range selection
The first thing I did was place an attenuator on the CV -- this does (in effect) what the 'range' on JW Modules Gridseq does -- attenuates the voltage before the quantizer.

You only need two knobs to handle all the pitch range issues -- offset and scale. The CV value:
Vout = Offset + (Scale * Vin)
Bonus points -- make them CV Controllable, (with attenuation, naturally) 

> Accept polyphonic triggers
That means you're tracing more than one path through the pyramid, which is ok but it brings up my main suggestion:

Add a gate sequencer.  You could actually re-use most of Darius' UI, but instead of a CV knob, have a button, so that when the path through the pyramid hits a step with the button pressed, it sends a trigger.  You could call it Milhaud (after the French composer Darius Milhaud)

As with Darius, if you accept polyphonic triggers you can trace multiple paths through the pyramid.

**Comment by AriaSalvatrice** [comment]
Please see issue #8 for a possible expanded successor that would add some amount of complexity - I don't want to make the existing module any more complex to use than it is now.

**Comment by AriaSalvatrice** [comment]
After thinking about it, the following will be added to Darius, and nothing else to keep it a beginner-friendly device:

- Unipolar/Bipolar rocker switch
- Step back input
- Accept triggers on any polyphonic channel

See #8 for a possible kitchen sink version.

**Comment by AriaSalvatrice** [comment]
Considering #16 too, despite increasing complexity, it addresses multiple drawbacks of the current implementation.

**Comment by AriaSalvatrice** [comment]
Added to Darius:
- All trigger inputs now accept polyphonic input. Existing patches are very unlikely to be broken by this new feature. If they are, they can be fixed by splitting any polyphonic trigger input then sending only the first channel.
- Added a "RND" seed CV input, and a switch to decide to refresh it on "1st/all" step(s), to force a specific random seed to be used.
- Added a CV range selector: 0V10V or -5V5V. CV Knobs now default to the center on new instances for ease of use in -5V~5V mode.
- Added new trigger controls: Back, Up, and Down. The "Step" CV input is now called "Forward" for consistency.

I'm satisfied that it probably should not get more features.
