### ISSUE TITLE
Randomize knobs on Darius do not get stored in Undo history

### ISSUE THREAD

**Issue by AriaSalvatrice** [AriaSalvatrice/AriaVCVModules#14]
Haven't looked into how to implement it yet

**Comment by AriaSalvatrice** [comment]
https://community.vcvrack.com/t/custom-history-actions-for-modules/2575

**Comment by AriaSalvatrice** [comment]
Pushing back that one for later. Anyone knows of open-source modules that implemented this so I can see what they did?

**Comment by david-c14** [comment]
https://github.com/david-c14/SubmarineFree/blob/1f8d55eccb8997ef42551afc9519e7cabb4cbcae/src/LT1.cpp#L427

Adding an Action to the APP-history.   However, this example uses anonymous functions, because I prefer them. The EventWidgetAction is defined [here](https://github.com/david-c14/SubmarineFree/blob/1f8d55eccb8997ef42551afc9519e7cabb4cbcae/src/shared/components.hpp#L411) and [here](https://github.com/david-c14/SubmarineFree/blob/1f8d55eccb8997ef42551afc9519e7cabb4cbcae/src/shared/EventWidgets.cpp#L4)

If you don't want to be doing anonymous functions, you need a subclass of ModuleAction for each kind of undo that you need,  create an instance of your subclass, give it whatever information it needs to undo / redo the action, and then add it to the APP->history.

Don't put a pointer to your module into the action, set the moduleId in the action instead, and then the undo/redo methods should find that module by it's id.   That's because your undo might get called after someone has deleted your module and then undone the delete, so your pointer would be invalid, but the id should be good.

**Comment by AriaSalvatrice** [comment]
Undo support was added to the development branch. 
Thank you for the example implementation @david-c14 !
