### ISSUE TITLE
native linux compile patch

### ISSUE THREAD

**Issue by hexdump0815** [AriaSalvatrice/AriaVCVModules#61]
hello,

to get your plugin (current vcvrack library submitted git commit hash) compiled natively on linux (aarch64 in my case but it should apply to intel linux as well i guess) i needed the following patch to get it compile: https://github.com/hexdump0815/vcvrack-dockerbuild-v1/blob/master/AriaSalvatrice.aarch64.patch ... maybe i'm doing something wrong or maybe it is really required ...

best wishes - hexdump

**Comment by AriaSalvatrice** [comment]
Thank you, I'll look into integrating the changes. The Makefile has a bunch of edits I don't fully understand to to support VCV's cross-compilation system so I'll have to look into things in detail before I can integrate the patch.

BTW, does the QQQQ module work properly on the Sonaremin after applying this patch? It's the first time my module is built on ARM and QuickJS gave us a lot of trouble to integrate. Clicking its keyboard button and writing down a chord is what triggers JS evaluation.

**Comment by AriaSalvatrice** [comment]
Applying the patch appears to work - it builds on my machine and on Azure CI. But it might break the VCV library build system. If it does, I'll have to revert those changes or we will have to figure out another solution. I'll let you know whether your patch could be applied or not next time I submit to the library.

**Comment by hexdump0815** [comment]
thanks a lot for the update - lets see if it works, but in theory it should i guess ...

**Comment by AriaSalvatrice** [comment]
It looks like the changes were accepted by the library since it passed review, so I guess you will no longer need this patch for version 1.7.0+ (I'll re-open this issue and notify you otherwise)

BTW I notice you maintain a second `armv7l.patch` patch for my plugin, but I assume it's a Sonaremin-specific patch that doesn't need to be merged upstream right?

Anyway, if QQQQ JS evaluation breaks on your platform, please open an issue. I probably won't be able to fix it but I'd like to know if it breaks. You can test it by writing down chords and pressing enter after clicking this button: 

![image](https://user-images.githubusercontent.com/25130242/90464832-719b0d00-e10e-11ea-8355-a06c177ad200.png)

**Comment by hexdump0815** [comment]
thanks for the testing hint - will do that some time soon

**Comment by hexdump0815** [comment]
test passed on both 32bit armv7l and 64bit aarch64 :)
